import Providers from '@/components/providers'
import '../styles/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets : ["latin"] , weight : ['100','200','300','400','500','600','700','900',]})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + " font-medium"}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
